/**
 * @ponchia/ui — typed class-name contract.
 *
 * The framework's real API is its class vocabulary. Hand-writing
 * "ui-button ui-button--ghost" everywhere is untyped and typo-prone, so
 * this module turns that contract into data + tiny recipe builders:
 *
 *   import { ui, cx } from '@ponchia/ui/classes';
 *   <button class={ui.button({ variant: 'ghost' })}>
 *   <span class={cx(ui.dot({ tone: 'success' }), 'my-extra')}>
 *
 * Framework-agnostic (returns strings). `cls` is the flat registry of
 * every class the framework defines; recipes only ever emit from it, and
 * scripts/check-classes.mjs fails CI if any entry is missing from the
 * stylesheet — so this file cannot drift from the CSS.
 */

/** Every class @ponchia/ui defines. The single source the recipes draw from. */
export const cls = Object.freeze({
  // primitives
  button: 'ui-button',
  buttonGhost: 'ui-button--ghost',
  buttonSubtle: 'ui-button--subtle',
  buttonDanger: 'ui-button--danger',
  buttonIcon: 'ui-button--icon',
  buttonSm: 'ui-button--sm',
  buttonLg: 'ui-button--lg',
  card: 'ui-card',
  cardHead: 'ui-card__head',
  cardAccent: 'ui-card--accent',
  cardInteractive: 'ui-card--interactive',
  stat: 'ui-stat',
  statgrid: 'ui-statgrid',
  statLabel: 'ui-stat__label',
  statValue: 'ui-stat__value',
  statDelta: 'ui-stat__delta',
  num: 'ui-num',
  numPos: 'ui-num--pos',
  numNeg: 'ui-num--neg',
  numMuted: 'ui-num--muted',
  badge: 'ui-badge',
  badgeAccent: 'ui-badge--accent',
  badgeSuccess: 'ui-badge--success',
  badgeWarning: 'ui-badge--warning',
  badgeDanger: 'ui-badge--danger',
  badgeInfo: 'ui-badge--info',
  badgeMuted: 'ui-badge--muted',
  badgeDot: 'ui-badge--dot',
  chip: 'ui-chip',
  chipAccent: 'ui-chip--accent',
  link: 'ui-link',
  linkArrow: 'ui-link--arrow',
  linkCta: 'ui-link--cta',
  keyValue: 'ui-key-value',
  emptyState: 'ui-empty-state',
  // dots
  dot: 'ui-dot',
  dotAccent: 'ui-dot--accent',
  dotSuccess: 'ui-dot--success',
  dotWarning: 'ui-dot--warning',
  dotDanger: 'ui-dot--danger',
  dotInfo: 'ui-dot--info',
  dotLive: 'ui-dot--live',
  dotgrid: 'ui-dotgrid',
  dotgridAccent: 'ui-dotgrid--accent',
  dotgridDense: 'ui-dotgrid--dense',
  dotmatrix: 'ui-dotmatrix',
  dotmatrixCell: 'ui-dotmatrix__cell',
  dotmatrixCellHot: 'ui-dotmatrix__cell--hot',
  dotmatrixCellAccent: 'ui-dotmatrix__cell--accent',
  dotmatrixReveal: 'ui-dotmatrix--reveal',
  dotmatrixPulse: 'ui-dotmatrix--pulse',
  icon: 'ui-icon',
  dotfield: 'ui-dotfield',
  dotrule: 'ui-dotrule',
  dotbar: 'ui-dotbar',
  dotbarIndeterminate: 'ui-dotbar--indeterminate',
  dotloader: 'ui-dotloader',
  dotspinner: 'ui-dotspinner',
  dotspinnerSm: 'ui-dotspinner--sm',
  dotspinnerLg: 'ui-dotspinner--lg',
  // forms
  field: 'ui-field',
  label: 'ui-label',
  input: 'ui-input',
  select: 'ui-select',
  textarea: 'ui-textarea',
  search: 'ui-search',
  check: 'ui-check',
  switch: 'ui-switch',
  switchTrack: 'ui-switch__track',
  switchThumb: 'ui-switch__thumb',
  hint: 'ui-hint',
  hintError: 'ui-hint--error',
  inputGroup: 'ui-input-group',
  inputGroupAddon: 'ui-input-group__addon',
  inputIcon: 'ui-input-icon',
  inputIconSlot: 'ui-input-icon__icon',
  inputIconEnd: 'ui-input-icon--end',
  file: 'ui-file',
  range: 'ui-range',
  errorSummary: 'ui-error-summary',
  errorSummaryTitle: 'ui-error-summary__title',
  errorSummaryList: 'ui-error-summary__list',
  // feedback
  alert: 'ui-alert',
  alertTitle: 'ui-alert__title',
  alertBody: 'ui-alert__body',
  alertDismiss: 'ui-alert__dismiss',
  alertAccent: 'ui-alert--accent',
  alertSuccess: 'ui-alert--success',
  alertWarning: 'ui-alert--warning',
  alertDanger: 'ui-alert--danger',
  alertInfo: 'ui-alert--info',
  toastStack: 'ui-toast-stack',
  toastStackAssertive: 'ui-toast-stack--assertive',
  toast: 'ui-toast',
  toastTitle: 'ui-toast__title',
  toastClose: 'ui-toast__close',
  toastAccent: 'ui-toast--accent',
  toastSuccess: 'ui-toast--success',
  toastWarning: 'ui-toast--warning',
  toastDanger: 'ui-toast--danger',
  toastInfo: 'ui-toast--info',
  tooltip: 'ui-tooltip',
  tooltipBubble: 'ui-tooltip__bubble',
  popover: 'ui-popover',
  progress: 'ui-progress',
  progressBar: 'ui-progress__bar',
  progressIndeterminate: 'ui-progress--indeterminate',
  meter: 'ui-meter',
  meterFill: 'ui-meter__fill',
  meterAccent: 'ui-meter--accent',
  meterSuccess: 'ui-meter--success',
  meterWarning: 'ui-meter--warning',
  meterDanger: 'ui-meter--danger',
  steps: 'ui-steps',
  stepsItem: 'ui-steps__item',
  stepsItemDone: 'ui-steps__item--done',
  // overlay
  modal: 'ui-modal',
  modalHead: 'ui-modal__head',
  modalTitle: 'ui-modal__title',
  modalBody: 'ui-modal__body',
  modalFoot: 'ui-modal__foot',
  modalClose: 'ui-modal__close',
  modalDrawer: 'ui-modal--drawer',
  menuHost: 'ui-menu-host',
  menu: 'ui-menu',
  menuLabel: 'ui-menu__label',
  menuItem: 'ui-menu__item',
  menuSep: 'ui-menu__sep',
  combobox: 'ui-combobox',
  comboboxInput: 'ui-combobox__input',
  comboboxList: 'ui-combobox__list',
  comboboxOption: 'ui-combobox__option',
  comboboxEmpty: 'ui-combobox__empty',
  lightbox: 'ui-lightbox',
  lightboxClose: 'ui-lightbox__close',
  // disclosure
  tabs: 'ui-tabs',
  tabsList: 'ui-tabs__list',
  tab: 'ui-tab',
  tabsPanel: 'ui-tabs__panel',
  accordion: 'ui-accordion',
  accordionItem: 'ui-accordion__item',
  accordionSummary: 'ui-accordion__summary',
  accordionBody: 'ui-accordion__body',
  segmented: 'ui-segmented',
  segmentedOption: 'ui-segmented__option',
  breadcrumb: 'ui-breadcrumb',
  breadcrumbItem: 'ui-breadcrumb__item',
  pagination: 'ui-pagination',
  paginationItem: 'ui-pagination__item',
  avatar: 'ui-avatar',
  avatarSm: 'ui-avatar--sm',
  avatarLg: 'ui-avatar--lg',
  avatarGroup: 'ui-avatar-group',
  carousel: 'ui-carousel',
  carouselStage: 'ui-carousel__stage',
  carouselViewport: 'ui-carousel__viewport',
  carouselSlide: 'ui-carousel__slide',
  carouselPrev: 'ui-carousel__prev',
  carouselNext: 'ui-carousel__next',
  carouselStatus: 'ui-carousel__status',
  carouselThumbs: 'ui-carousel__thumbs',
  carouselThumb: 'ui-carousel__thumb',
  // table
  table: 'ui-table',
  tableDense: 'ui-table--dense',
  tableComfortable: 'ui-table--comfortable',
  tableLined: 'ui-table--lined',
  tableWrap: 'ui-table-wrap',
  tableEmpty: 'ui-table__empty',
  tableSort: 'ui-table__sort',
  tableSelect: 'ui-table__select',
  tableToolbar: 'ui-table__toolbar',
  tableSelectable: 'ui-table--selectable',
  tableLoading: 'ui-table--loading',
  // shell / layout
  panel: 'ui-panel',
  panelHead: 'ui-panel__head',
  surface: 'ui-surface',
  stack: 'ui-stack',
  cluster: 'ui-cluster',
  clusterBetween: 'ui-cluster--between',
  grid: 'ui-grid',
  sidebar: 'ui-sidebar',
  switcher: 'ui-switcher',
  center: 'ui-center',
  ratio: 'ui-ratio',
  cq: 'ui-cq',
  divider: 'ui-divider',
  status: 'ui-status',
  // typography / utilities
  eyebrow: 'ui-eyebrow',
  eyebrowMuted: 'ui-eyebrow--muted',
  eyebrowSm: 'ui-eyebrow--sm',
  prose: 'ui-prose',
  proseCompact: 'ui-prose--compact',
  quote: 'ui-quote',
  quoteCite: 'ui-quote__cite',
  // site shell
  container: 'ui-container',
  containerNarrow: 'ui-container--narrow',
  containerWide: 'ui-container--wide',
  skiplink: 'ui-skiplink',
  siteheader: 'ui-siteheader',
  siteheaderSticky: 'ui-siteheader--sticky',
  siteheaderBrand: 'ui-siteheader__brand',
  siteheaderActions: 'ui-siteheader__actions',
  pagehead: 'ui-pagehead',
  pageheadTitle: 'ui-pagehead__title',
  pageheadActions: 'ui-pagehead__actions',
  sitenav: 'ui-sitenav',
  sitemenu: 'ui-sitemenu',
  sitemenuPanel: 'ui-sitemenu__panel',
  sitefooter: 'ui-sitefooter',
  sitefooterLinks: 'ui-sitefooter__links',
  tags: 'ui-tags',
  tag: 'ui-tag',
  tagAccent: 'ui-tag--accent',
  meta: 'ui-meta',
  metaItem: 'ui-meta__item',
  timeline: 'ui-timeline',
  timelineItem: 'ui-timeline__item',
  timelineTime: 'ui-timeline__time',
  // report kit (opt-in css/report.css)
  report: 'ui-report',
  reportCompact: 'ui-report--compact',
  reportNumbered: 'ui-report--numbered',
  reportCover: 'ui-report__cover',
  reportCoverCompact: 'ui-report__cover--compact',
  reportHeader: 'ui-report__header',
  reportTitle: 'ui-report__title',
  reportSubtitle: 'ui-report__subtitle',
  reportMeta: 'ui-report__meta',
  reportToc: 'ui-report__toc',
  reportSummary: 'ui-report__summary',
  reportSection: 'ui-report__section',
  reportSectionUnnumbered: 'ui-report__section--unnumbered',
  reportSectionHead: 'ui-report__section-head',
  reportFinding: 'ui-report__finding',
  reportEvidence: 'ui-report__evidence',
  reportFigure: 'ui-report__figure',
  reportCaption: 'ui-report__caption',
  reportSources: 'ui-report__sources',
  reportAppendix: 'ui-report__appendix',
  reportFootnotes: 'ui-report__footnotes',
  chart: 'ui-chart',
  chartCaption: 'ui-chart__caption',
  chartPlot: 'ui-chart__plot',
  chartBar: 'ui-chart__bar',
  chartLabel: 'ui-chart__label',
  chartTrack: 'ui-chart__track',
  chartFill: 'ui-chart__fill',
  chartFallback: 'ui-chart__fallback',
  // legend (standalone data keys — css/legend.css)
  legend: 'ui-legend',
  legendVertical: 'ui-legend--vertical',
  legendCompact: 'ui-legend--compact',
  legendGradient: 'ui-legend--gradient',
  legendDiverging: 'ui-legend--diverging',
  legendThreshold: 'ui-legend--threshold',
  legendWithValues: 'ui-legend--with-values',
  legendInteractive: 'ui-legend--interactive',
  legendTitle: 'ui-legend__title',
  legendItem: 'ui-legend__item',
  legendSwatch: 'ui-legend__swatch',
  legendSwatchCircle: 'ui-legend__swatch--circle',
  legendSwatchLine: 'ui-legend__swatch--line',
  legendSwatch1: 'ui-legend__swatch--1',
  legendSwatch2: 'ui-legend__swatch--2',
  legendSwatch3: 'ui-legend__swatch--3',
  legendSwatch4: 'ui-legend__swatch--4',
  legendSwatch5: 'ui-legend__swatch--5',
  legendSwatch6: 'ui-legend__swatch--6',
  legendSwatch7: 'ui-legend__swatch--7',
  legendSwatch8: 'ui-legend__swatch--8',
  legendSymbol: 'ui-legend__symbol',
  legendLabel: 'ui-legend__label',
  legendValue: 'ui-legend__value',
  legendCaption: 'ui-legend__caption',
  legendTrack: 'ui-legend__track',
  legendTicks: 'ui-legend__ticks',
  legendTick: 'ui-legend__tick',
  annotation: 'ui-annotation',
  annotationSubject: 'ui-annotation__subject',
  annotationConnector: 'ui-annotation__connector',
  annotationConnectorEnd: 'ui-annotation__connector-end',
  annotationNote: 'ui-annotation__note',
  annotationNoteLine: 'ui-annotation__note-line',
  annotationTitle: 'ui-annotation__title',
  annotationLabel: 'ui-annotation__label',
  annotationBadge: 'ui-annotation__badge',
  annotationLabelVariant: 'ui-annotation--label',
  annotationCallout: 'ui-annotation--callout',
  annotationElbow: 'ui-annotation--elbow',
  annotationCurve: 'ui-annotation--curve',
  annotationCircle: 'ui-annotation--circle',
  annotationRect: 'ui-annotation--rect',
  annotationThreshold: 'ui-annotation--threshold',
  annotationBadgeVariant: 'ui-annotation--badge',
  annotationBracket: 'ui-annotation--bracket',
  annotationBand: 'ui-annotation--band',
  annotationSlope: 'ui-annotation--slope',
  annotationCompare: 'ui-annotation--compare',
  annotationCluster: 'ui-annotation--cluster',
  annotationAxis: 'ui-annotation--axis',
  annotationTimeline: 'ui-annotation--timeline',
  annotationEvidence: 'ui-annotation--evidence',
  annotationAccent: 'ui-annotation--accent',
  annotationMuted: 'ui-annotation--muted',
  annotationSuccess: 'ui-annotation--success',
  annotationWarning: 'ui-annotation--warning',
  annotationDanger: 'ui-annotation--danger',
  annotationInfo: 'ui-annotation--info',
  annotationDraw: 'ui-annotation--draw',
  annotationPulse: 'ui-annotation--pulse',
  annotationReveal: 'ui-annotation--reveal',
  annotationFocus: 'ui-annotation--focus',
  // marks (evidence/emphasis for running text — css/marks.css)
  mark: 'ui-mark',
  markEvidence: 'ui-mark--evidence',
  markSuccess: 'ui-mark--success',
  markWarning: 'ui-mark--warning',
  markDanger: 'ui-mark--danger',
  markInfo: 'ui-mark--info',
  markMuted: 'ui-mark--muted',
  markUnderline: 'ui-mark--underline',
  markBox: 'ui-mark--box',
  markStrike: 'ui-mark--strike',
  markDraw: 'ui-mark--draw',
  bracketNote: 'ui-bracket-note',
  bracketNoteLabel: 'ui-bracket-note__label',
  bracketNoteEvidence: 'ui-bracket-note--evidence',
  bracketNoteWarning: 'ui-bracket-note--warning',
  bracketNoteDanger: 'ui-bracket-note--danger',
  bracketNoteInfo: 'ui-bracket-note--info',
  // connectors (leader lines — css/connectors.css)
  connector: 'ui-connector',
  connectorPath: 'ui-connector__path',
  connectorEnd: 'ui-connector__end',
  connectorDashed: 'ui-connector--dashed',
  connectorAccent: 'ui-connector--accent',
  connectorMuted: 'ui-connector--muted',
  connectorSuccess: 'ui-connector--success',
  connectorWarning: 'ui-connector--warning',
  connectorDanger: 'ui-connector--danger',
  connectorInfo: 'ui-connector--info',
  connectorDraw: 'ui-connector--draw',
  // spotlight (guided-focus overlay — css/spotlight.css)
  spotlight: 'ui-spotlight',
  spotlightHole: 'ui-spotlight__hole',
  spotlightRing: 'ui-spotlight--ring',
  tourNote: 'ui-tour-note',
  tourNoteStep: 'ui-tour-note__step',
  tourNoteTitle: 'ui-tour-note__title',
  tourNoteBody: 'ui-tour-note__body',
  tourNoteActions: 'ui-tour-note__actions',
  printOnly: 'ui-print-only',
  screenOnly: 'ui-screen-only',
  breakBefore: 'ui-break-before',
  breakAfter: 'ui-break-after',
  keep: 'ui-keep',
  printExact: 'ui-print-exact',
  kbd: 'ui-kbd',
  display: 'ui-display',
  mono: 'ui-mono',
  muted: 'ui-muted',
  visuallyHidden: 'ui-visually-hidden',
  // motion
  reveal: 'ui-reveal',
  stagger: 'ui-stagger',
  staggerAuto: 'ui-stagger--auto',
  matrix: 'ui-matrix',
  skeleton: 'ui-skeleton',
  spinner: 'ui-spinner',
  caret: 'ui-caret',
  animateIn: 'ui-animate-in',
  animateFade: 'ui-animate-fade',
  animateDot: 'ui-animate-dot',
  animateMatrix: 'ui-animate-matrix',
  scrollProgress: 'ui-scroll-progress',
  scrollReveal: 'ui-scroll-reveal',
  vt: 'ui-vt',
  // admin shell (was the legacy .app-* vocabulary; promoted in 0.3.0)
  appShell: 'ui-app-shell',
  appShellFull: 'ui-app-shell--full',
  appRail: 'ui-app-rail',
  appRailBrand: 'ui-app-rail__brand',
  appRailToggle: 'ui-app-rail__toggle',
  appRailFoot: 'ui-app-rail__foot',
  appRailAccount: 'ui-app-rail__account',
  appTopbar: 'ui-app-topbar',
  appTopbarTitle: 'ui-app-topbar__title',
  appToolbar: 'ui-app-toolbar',
  appToolbarGroup: 'ui-app-toolbar__group',
  appNav: 'ui-app-nav',
  appNavSection: 'ui-app-nav__section',
  appMain: 'ui-app-main',
  appContent: 'ui-app-content',
  appPanel: 'ui-app-panel',
  appPanelHead: 'ui-app-panel__head',
  appPanelTitle: 'ui-app-panel__title',
  appMetrics: 'ui-app-metrics',
  appMetric: 'ui-app-metric',
  appMetricLabel: 'ui-app-metric__label',
  appMetricValue: 'ui-app-metric__value',
  appMetricDelta: 'ui-app-metric__delta',
  appEmptyState: 'ui-app-empty-state',
  // theme toggle (was the legacy .theme-toggle__* vocabulary)
  themetoggleButton: 'ui-themetoggle__button',
  themetogglePrefix: 'ui-themetoggle__prefix',
  themetoggleLabel: 'ui-themetoggle__label',
  themetoggleTrack: 'ui-themetoggle__track',
  themetoggleThumb: 'ui-themetoggle__thumb',
});

/** classnames-style joiner: skips falsy, flattens nested arrays of any depth. */
export function cx(...parts) {
  const out = [];
  for (const p of parts.flat(Infinity)) if (p) out.push(p);
  return out.join(' ');
}

const j = (...p) => p.filter(Boolean).join(' ');

export const ui = {
  button: ({ variant, icon, size } = {}) =>
    j(
      cls.button,
      variant === 'ghost' && cls.buttonGhost,
      variant === 'subtle' && cls.buttonSubtle,
      variant === 'danger' && cls.buttonDanger,
      icon && cls.buttonIcon,
      size === 'sm' && cls.buttonSm,
      size === 'lg' && cls.buttonLg,
    ),
  card: ({ accent, interactive } = {}) =>
    j(cls.card, accent && cls.cardAccent, interactive && cls.cardInteractive),
  badge: ({ tone, dot } = {}) =>
    j(
      cls.badge,
      tone === 'accent' && cls.badgeAccent,
      tone === 'success' && cls.badgeSuccess,
      tone === 'warning' && cls.badgeWarning,
      tone === 'danger' && cls.badgeDanger,
      tone === 'info' && cls.badgeInfo,
      tone === 'muted' && cls.badgeMuted,
      dot && cls.badgeDot,
    ),
  num: ({ tone } = {}) =>
    j(
      cls.num,
      tone === 'pos' && cls.numPos,
      tone === 'neg' && cls.numNeg,
      tone === 'muted' && cls.numMuted,
    ),
  chip: ({ accent } = {}) => j(cls.chip, accent && cls.chipAccent),
  link: ({ arrow, cta } = {}) => j(cls.link, arrow && cls.linkArrow, cta && cls.linkCta),
  dot: ({ tone, live } = {}) =>
    j(
      cls.dot,
      tone === 'accent' && cls.dotAccent,
      tone === 'success' && cls.dotSuccess,
      tone === 'warning' && cls.dotWarning,
      tone === 'danger' && cls.dotDanger,
      tone === 'info' && cls.dotInfo,
      live && cls.dotLive,
    ),
  dotgrid: ({ accent, dense } = {}) =>
    j(cls.dotgrid, accent && cls.dotgridAccent, dense && cls.dotgridDense),
  table: ({ density, lined } = {}) =>
    j(
      cls.table,
      density === 'dense' && cls.tableDense,
      density === 'comfortable' && cls.tableComfortable,
      lined && cls.tableLined,
    ),
  eyebrow: ({ muted, sm } = {}) => j(cls.eyebrow, muted && cls.eyebrowMuted, sm && cls.eyebrowSm),
  hint: ({ error } = {}) => j(cls.hint, error && cls.hintError),
  cluster: ({ between } = {}) => j(cls.cluster, between && cls.clusterBetween),
  stagger: ({ auto } = {}) => j(cls.stagger, auto && cls.staggerAuto),
  alert: ({ tone } = {}) =>
    j(
      cls.alert,
      tone === 'accent' && cls.alertAccent,
      tone === 'success' && cls.alertSuccess,
      tone === 'warning' && cls.alertWarning,
      tone === 'danger' && cls.alertDanger,
      tone === 'info' && cls.alertInfo,
    ),
  toast: ({ tone } = {}) =>
    j(
      cls.toast,
      tone === 'accent' && cls.toastAccent,
      tone === 'success' && cls.toastSuccess,
      tone === 'warning' && cls.toastWarning,
      tone === 'danger' && cls.toastDanger,
      tone === 'info' && cls.toastInfo,
    ),
  progress: ({ indeterminate } = {}) => j(cls.progress, indeterminate && cls.progressIndeterminate),
  meter: ({ tone } = {}) =>
    j(
      cls.meter,
      tone === 'accent' && cls.meterAccent,
      tone === 'success' && cls.meterSuccess,
      tone === 'warning' && cls.meterWarning,
      tone === 'danger' && cls.meterDanger,
    ),
  dotspinner: ({ size } = {}) =>
    j(cls.dotspinner, size === 'sm' && cls.dotspinnerSm, size === 'lg' && cls.dotspinnerLg),
  dotbar: ({ indeterminate } = {}) => j(cls.dotbar, indeterminate && cls.dotbarIndeterminate),
  modal: ({ drawer, open } = {}) => j(cls.modal, drawer && cls.modalDrawer, open && 'is-open'),
  tab: ({ active } = {}) => j(cls.tab, active && 'is-active'),
  avatar: ({ size } = {}) =>
    j(cls.avatar, size === 'sm' && cls.avatarSm, size === 'lg' && cls.avatarLg),
  prose: ({ compact } = {}) => j(cls.prose, compact && cls.proseCompact),
  container: ({ narrow, wide } = {}) =>
    j(cls.container, narrow && cls.containerNarrow, wide && cls.containerWide),
  tag: ({ accent } = {}) => j(cls.tag, accent && cls.tagAccent),
  inputIcon: ({ end } = {}) => j(cls.inputIcon, end && cls.inputIconEnd),
  legend: ({ orient, type, diverging, compact, withValues, interactive } = {}) =>
    j(
      cls.legend,
      orient === 'vertical' && cls.legendVertical,
      type === 'gradient' && cls.legendGradient,
      type === 'threshold' && cls.legendThreshold,
      diverging && cls.legendDiverging,
      compact && cls.legendCompact,
      withValues && cls.legendWithValues,
      interactive && cls.legendInteractive,
    ),
  legendItem: ({ inactive } = {}) => j(cls.legendItem, inactive && 'is-inactive'),
  legendSwatch: ({ series, shape } = {}) =>
    j(
      cls.legendSwatch,
      series === 1 && cls.legendSwatch1,
      series === 2 && cls.legendSwatch2,
      series === 3 && cls.legendSwatch3,
      series === 4 && cls.legendSwatch4,
      series === 5 && cls.legendSwatch5,
      series === 6 && cls.legendSwatch6,
      series === 7 && cls.legendSwatch7,
      series === 8 && cls.legendSwatch8,
      shape === 'circle' && cls.legendSwatchCircle,
      shape === 'line' && cls.legendSwatchLine,
    ),
  annotation: ({ variant = 'callout', tone = 'accent', motion } = {}) =>
    j(
      cls.annotation,
      variant === 'label' && cls.annotationLabelVariant,
      variant === 'callout' && cls.annotationCallout,
      variant === 'elbow' && cls.annotationElbow,
      variant === 'curve' && cls.annotationCurve,
      variant === 'circle' && cls.annotationCircle,
      variant === 'rect' && cls.annotationRect,
      variant === 'threshold' && cls.annotationThreshold,
      variant === 'badge' && cls.annotationBadgeVariant,
      variant === 'bracket' && cls.annotationBracket,
      variant === 'band' && cls.annotationBand,
      variant === 'slope' && cls.annotationSlope,
      variant === 'compare' && cls.annotationCompare,
      variant === 'cluster' && cls.annotationCluster,
      variant === 'axis' && cls.annotationAxis,
      variant === 'timeline' && cls.annotationTimeline,
      variant === 'evidence' && cls.annotationEvidence,
      tone === 'accent' && cls.annotationAccent,
      tone === 'muted' && cls.annotationMuted,
      tone === 'success' && cls.annotationSuccess,
      tone === 'warning' && cls.annotationWarning,
      tone === 'danger' && cls.annotationDanger,
      tone === 'info' && cls.annotationInfo,
      motion === 'draw' && cls.annotationDraw,
      motion === 'pulse' && cls.annotationPulse,
      motion === 'reveal' && cls.annotationReveal,
      motion === 'focus' && cls.annotationFocus,
    ),
  mark: ({ style, tone, motion } = {}) =>
    j(
      cls.mark,
      style === 'underline' && cls.markUnderline,
      style === 'box' && cls.markBox,
      style === 'strike' && cls.markStrike,
      tone === 'evidence' && cls.markEvidence,
      tone === 'success' && cls.markSuccess,
      tone === 'warning' && cls.markWarning,
      tone === 'danger' && cls.markDanger,
      tone === 'info' && cls.markInfo,
      tone === 'muted' && cls.markMuted,
      motion === 'draw' && cls.markDraw,
    ),
  bracketNote: ({ tone } = {}) =>
    j(
      cls.bracketNote,
      tone === 'evidence' && cls.bracketNoteEvidence,
      tone === 'warning' && cls.bracketNoteWarning,
      tone === 'danger' && cls.bracketNoteDanger,
      tone === 'info' && cls.bracketNoteInfo,
    ),
  connector: ({ tone, dashed, motion } = {}) =>
    j(
      cls.connector,
      tone === 'accent' && cls.connectorAccent,
      tone === 'muted' && cls.connectorMuted,
      tone === 'success' && cls.connectorSuccess,
      tone === 'warning' && cls.connectorWarning,
      tone === 'danger' && cls.connectorDanger,
      tone === 'info' && cls.connectorInfo,
      dashed && cls.connectorDashed,
      motion === 'draw' && cls.connectorDraw,
    ),
  spotlight: ({ ring } = {}) => j(cls.spotlight, ring && cls.spotlightRing),
};

export default ui;
