/**
 * @ponchia/ui — optional display colorways ("skins").
 *
 * The single source for the opt-in `data-bronto-skin` looks (ADR-0001 step 4).
 * A skin is NOT a second brand colour — it *re-points the one accent* (and the
 * Tier-3 dot-matrix display knobs) to a different single hue, so the
 * one-accent-per-scope discipline holds while the palette gains creative range
 * *across* skins. The neutral canvas, status palette, and every component stay
 * exactly as they are.
 *
 * Accents are authored in **OKLCH** (ADR-0001 step 5 — "OKLCH for new work
 * first"): perceptually-uniform lightness makes the light/dark pair easy to
 * reason about, and it is comfortably within the package browser floor
 * (Chrome 125+ / Safari 18+ / Firefox 129+ per ADR-0002 — `oklch()` and
 * `color-mix()` in fact landed even earlier, Chrome 111 / Safari 16.4 / FF 121).
 *
 * Each skin gives a per-theme accent because — exactly like the core red
 * (#d71921 light / #ff3b41 dark) — one hue cannot stay AA against both a white
 * and a black button label; the light accent is darker, the dark one brighter.
 * The derived family (`--accent-strong`/`-text`/`-soft`, `--focus-ring`,
 * `--bg-accent`, `--field-dot-accent`) recomputes in the browser from the live
 * `var(--accent)`, so a skin only sets `--accent` plus any display knobs.
 *
 * This module is the source for BOTH:
 *   - css/skins.css           (generated by scripts/gen-skins.mjs, drift-checked)
 *   - the skin contrast audit (scripts/gen-contrast.mjs gates every skin accent)
 *
 * Skins are shipped OPT-IN: a separate `./css/skins.css` entrypoint, never part
 * of the default `dist/bronto.css` bundle.
 */

/**
 * name → { label, light, dark }. `light`/`dark` are CSS custom-property maps
 * applied under the same conditions as the core light/dark palettes. Keep the
 * key set of light and dark identical (a drift check enforces it).
 */
export const skins = {
  'amber-crt': {
    label: 'Amber CRT',
    // Phosphor amber. Dark+saturated in light theme (AA under a white label),
    // bright with a warm bloom in dark theme (the classic CRT glow).
    light: { '--accent': 'oklch(52% 0.11 67deg)' },
    dark: { '--accent': 'oklch(82% 0.15 82deg)', '--dotmatrix-glow': '0.4em' },
  },
  'phosphor-green': {
    label: 'Phosphor Green',
    // P1-phosphor green. Same light=dark-ink / dark=bright-glow split.
    light: { '--accent': 'oklch(52% 0.13 150deg)' },
    dark: { '--accent': 'oklch(84% 0.19 150deg)', '--dotmatrix-glow': '0.4em' },
  },
  'e-ink': {
    label: 'E-ink',
    // The opposite move: drop the hue almost entirely → a near-monochrome
    // ink/paper accent, no glow. The most restrained look in the set.
    light: { '--accent': 'oklch(34% 0.012 250deg)' },
    dark: { '--accent': 'oklch(84% 0.008 250deg)' },
  },
};

/** Skin names, frozen + sorted. */
export const SKIN_NAMES = Object.freeze(Object.keys(skins).sort());

export default skins;
