/**
 * Author-time emitter for an inlineable foreign-renderer theme literal.
 *
 * The Vega / Mermaid / D2 theme helpers (`@ponchia/ui/vega` …) are JS, so a
 * report opened straight from disk (`file://`) cannot `import` them — the
 * portable path is to paste the *resolved* object inline. This mirrors the
 * annotations author-time-copy pattern (docs/annotations.md): run a helper once
 * at author/build time, paste the deterministic string into the static HTML.
 *
 * Two modes:
 *   emit  — `node scripts/emit-theme.mjs <vega|mermaid|d2> <light|dark> [--name X]`
 *           prints a sentinel-wrapped `const … = { … };` block to copy in.
 *   check — `node scripts/emit-theme.mjs --check [file|dir …]`
 *           re-derives every tagged block found and fails on drift. With no
 *           paths it scans the dogfood/report dirs. This is the local drift
 *           guard for inlined blocks (reports-lab is gitignored, so it is not a
 *           CI gate — the CI invariant that emit ≡ tokens lives in the test).
 *
 * A tagged block looks exactly like the emitter's output:
 *   /* @ponchia/ui:inline-theme:start vega light … *\/
 *   const brontoVegaLight = { …JSON… };
 *   /* @ponchia/ui:inline-theme:end *\/
 */
import { readFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { isDeepStrictEqual } from 'node:util';
import { brontoVegaConfig } from '../tokens/vega.js';
import { brontoMermaidTheme } from '../tokens/mermaid.js';
import { brontoD2Overrides } from '../tokens/d2.js';
import { reportAndExit } from './lib/gate-report.mjs';

import { repoRoot as root, isMain } from './lib/emit.mjs';

// target → { resolve(theme) → JSON-safe object, default var-name stem, what it feeds }
export const TARGETS = {
  vega: { resolve: brontoVegaConfig, stem: 'brontoVega', feeds: "vega-embed's `{ config }`" },
  mermaid: { resolve: brontoMermaidTheme, stem: 'brontoMermaid', feeds: 'mermaid.initialize(…)' },
  d2: { resolve: brontoD2Overrides, stem: 'brontoD2', feeds: "the D2 render API's themeOverrides" },
};

const cap = (s) => s[0].toUpperCase() + s.slice(1);

/** The resolved, JSON-safe theme object for a target/theme (throws on bad input). */
export function themeObject(target, theme) {
  const t = TARGETS[target];
  if (!t)
    throw new Error(`unknown target "${target}" (expected: ${Object.keys(TARGETS).join(', ')})`);
  if (theme !== 'light' && theme !== 'dark')
    throw new Error(`theme must be "light" or "dark", got "${theme}"`);
  return t.resolve(theme);
}

/** A sentinel-wrapped, paste-ready `const … = { … };` block for a file:// report. */
export function emitTheme(target, theme, { name } = {}) {
  const obj = themeObject(target, theme);
  const varName = name || `${TARGETS[target].stem}${cap(theme)}`;
  const body = JSON.stringify(obj, null, 2);
  return [
    `/* @ponchia/ui:inline-theme:start ${target} ${theme} — generated by ` +
      `\`npm run emit:theme ${target} ${theme}\`; feeds ${TARGETS[target].feeds}. ` +
      `Re-run after a token change. */`,
    `const ${varName} = ${body};`,
    `/* @ponchia/ui:inline-theme:end */`,
  ].join('\n');
}

const BLOCK =
  /@ponchia\/ui:inline-theme:start\s+(\w+)\s+(\w+)[\s\S]*?\*\/([\s\S]*?)\/\*\s*@ponchia\/ui:inline-theme:end/g;

/** Parse a file's source for tagged blocks; returns [{ target, theme, obj }]. */
export function parseBlocks(src) {
  const out = [];
  for (const m of src.matchAll(BLOCK)) {
    const [, target, theme, inner] = m;
    const open = inner.indexOf('{');
    const close = inner.lastIndexOf('}');
    out.push({ target, theme, inner, json: open !== -1 ? inner.slice(open, close + 1) : null });
  }
  return out;
}

/** Diff every tagged block in `src` against current tokens; returns error strings. */
export function checkSource(rel, src) {
  const errors = [];
  for (const b of parseBlocks(src)) {
    if (!TARGETS[b.target] || (b.theme !== 'light' && b.theme !== 'dark')) {
      errors.push(`${rel}: tagged block names unknown target/theme "${b.target} ${b.theme}"`);
      continue;
    }
    let parsed;
    try {
      parsed = JSON.parse(b.json);
    } catch (e) {
      errors.push(`${rel}: ${b.target} ${b.theme} block is not parseable JSON (${e.message})`);
      continue;
    }
    if (!isDeepStrictEqual(parsed, themeObject(b.target, b.theme))) {
      errors.push(
        `${rel}: inlined ${b.target} ${b.theme} theme has drifted from tokens — re-run \`npm run emit:theme ${b.target} ${b.theme}\``,
      );
    }
  }
  return errors;
}

function walk(rel) {
  const abs = resolve(root, rel);
  if (!existsSync(abs)) return [];
  if (statSync(abs).isFile()) return [rel];
  const out = [];
  for (const name of readdirSync(abs)) {
    if (name === 'node_modules' || name === 'dist' || name === '.git') continue;
    out.push(...walk(join(rel, name).replaceAll('\\', '/')));
  }
  return out;
}

function runCheck(paths) {
  const roots = paths.length ? paths : ['reports-lab', 'demo', 'examples/report-static'];
  const files = roots.flatMap(walk).filter((p) => /\.(html?|js|mjs|md|svg)$/.test(p));
  const errors = [];
  let tagged = 0;
  for (const rel of files) {
    const src = readFileSync(resolve(root, rel), 'utf8');
    if (!src.includes('@ponchia/ui:inline-theme:start')) continue;
    tagged += parseBlocks(src).length;
    errors.push(...checkSource(rel, src));
  }
  reportAndExit(errors, {
    label: 'inline-theme drift',
    ok:
      tagged > 0
        ? `inline-theme: ${tagged} tagged block(s) match current tokens`
        : `inline-theme: no tagged blocks found in ${roots.join(', ')} (nothing to drift)`,
  });
}

// CLI
if (isMain(import.meta.url)) {
  const argv = process.argv.slice(2);
  if (argv[0] === '--check') {
    runCheck(argv.slice(1));
  } else {
    const [target, theme] = argv;
    const nameIdx = argv.indexOf('--name');
    const name = nameIdx !== -1 ? argv[nameIdx + 1] : undefined;
    if (!target || !theme) {
      console.error('usage: node scripts/emit-theme.mjs <vega|mermaid|d2> <light|dark> [--name X]');
      console.error('       node scripts/emit-theme.mjs --check [file|dir …]');
      process.exit(1);
    }
    try {
      console.log(emitTheme(target, theme, { name }));
    } catch (e) {
      console.error(`✖ ${e.message}`);
      process.exit(1);
    }
  }
}
